# Used for configuring local dependencies only
version: '3.9'

services:
  db:
    image: postgres:15
    container_name: gradprep_db
    restart: on-failure
    environment:
      - POSTGRES_DB=gradprep
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - gradprep_db:/var/lib/postgresql/data
    ports:
      - "5434:5432"

volumes:
  gradprep_db: