import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";

import { api } from "@/utils/api";
import { Button } from "@/components/elements/Button";
import { SearchInput } from "@/components/elements/Search";
import { Input } from "@/components/elements/Input";

import Lottie from "lottie-react";
import Books from "../../public/assets/lottie/books-1.json"
import Connect from "../../public/assets/lottie/connect.json"
import Info from "../../public/assets/lottie/info.json"
import Quiz from "../../public/assets/lottie/quiz.json"
import { RiArrowLeftCircleFill, RiArrowRightCircleFill } from "react-icons/ri";

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Hero */}
      <main className="relative flex min-h-screen flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center pt-36">
          <div className=" rounded-full bg-[#5056ED]/[.42] w-[80vh] h-[80vh] absolute -top-48 -left-32 z-0"></div>
          <div className=" rounded-full bg-[#111692]/[.42] w-[50vh] h-[50vh] absolute top-64 -left-40 z-0"></div>
          <div className=" rounded-full bg-[#111692]/[.42] w-[40vh] h-[40vh] absolute bottom-12 -right-48 z-0"></div>
          <div className=" rounded-full bg-[#946CE8]/[.62] w-[64vh] h-[64vh] absolute -bottom-56 -right-24 z-0"></div>
          <h1>[H1] Persiapkan masa depanmu dalam waktu <span className=" text-primary italic">20 menit (use text-primary)</span>.</h1>
          <h2>[h2] This is heading 2.</h2>
          <h3>[h3] This is heading 3.</h3>
          <p>[p] This is normal paragraph text</p>
        </div>
        <div className="flex flex-col items-center gap-2">
          <p>
            {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          </p>
          <div className="grid grid-cols-2 gap-4">
            <Input />
            <SearchInput placeholder="This is a SearchInput" className="z-10"/>
          </div>
        </div>
      </main>

      {/* Section 2 */}
      <div className="relative h-[90vh] bg-primary justify-center flex flex-col items-center text-white">
        <div className="container flex flex-row">
          <Lottie animationData={Books} />
          <div className="max-w-[60%] flex flex-col justify-center">
            <h2>Apakah kamu siap menghadapi tantangan masa depan?</h2>
            <p>Untuk mematangkan diri menuju pendidikan pascasarjana, kamu dapat melakukan seluruh persiapanmu di GradPrep! Platform kami adalah <i>one-stop solution</i> untuk meraih cita-cita masa depanmu.</p>
          </div>
        </div>
      </div>

      {/* Section 3 */}
      <div className="relative h-[90vh] bg-white justify-center flex flex-col items-center">
        <h2 className="container text-center mb-12">Semua kebutuhanmu di satu platform.</h2>
        <div className="container flex flex-row justify-center gap-x-12">
            <div className="w-[18vw]">
              <div className="w-[50%] mx-auto"><Lottie animationData={Quiz} /></div>
              <p>Uji kemampuanmu dengan <u>Mock Test</u> !</p>
            </div>
            <div className="w-[18vw]">
              <div className="w-[50%] mx-auto"><Lottie animationData={Info} /></div>
              <p>Temukan semua informasi terkait <u>beasiswa dan program S2/S3</u> yang kamu butuhkan.</p>
            </div>
            <div className="w-[18vw]">
              <div className="w-[50%] mx-auto"><Lottie animationData={Connect} /></div>
              <p>Butuh bantuan? Tanyakan ke <u>Mentor</u> kami.</p>
            </div>
        </div>
      </div>

      {/* Section 4 */}
      <div className="relative h-[90vh] bg-primary justify-start flex flex-col items-center text-white">
        <div className="container relative -top-[10vh] h-[20vh] bg-white text-black shadow-lg shadow-gray-700 justify-center flex flex-col items-center rounded-[15px] p-20">
          <h2>Awooga</h2>
          <div className="flex flex-row justify-around gap-x-2">
            <p>carousel item</p>
            <p>carousel item</p>
            <p>carousel item</p>
            <p>carousel item</p>
            <p>carousel item</p>
          </div>
        </div>
        <h2 className="container text-center">Kata Mereka</h2>
        <div className="container flex flex-row justify-center gap-x-12">
            <button className="active:scale-[0.85] transition-all">
              <RiArrowLeftCircleFill size={48}/>
            </button>
            <div className="w-[30vw] text-center">
              <div className="w-[50%] mx-auto"><Lottie animationData={Info} /></div>
              <p className="font-bold">I really like it, Very Good Platform</p>
              <p>Take the edit distance calculated between the previous substrings and increment it only if their currently processing chars differ (hypothetical necessary substitution).</p>
            </div>
            <button className="active:scale-[0.85] transition-all">
              <RiArrowRightCircleFill size={48}/>
            </button>
        </div>
      </div>

      <div className="relative h-[90vh] bg-white justify-center flex flex-col items-center">
        <div className="container text-center mb-12">
          <h2>Coba <span className="font-bold underline italic">sekarang juga</span>.</h2>
          <p>Gada salahnya kan coba-coba?</p>
        </div>
        <Button variant={"primary"} size={"md"}>
          Daftar Sekarang
        </Button>
      </div>
    </>
  );
}
