import { GenericCard, Button } from "@/components/elements";
import { useSession, signOut } from 'next-auth/react';
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useEffect } from "react";

export default function LogoutPage() {
  const { data: sessionData } = useSession();
  const router = useRouter()

  useEffect(() => {
    sessionData ? void signOut : ''
    setTimeout(() => {
      void router.push("/")
    }, 2500)
  }, [router, sessionData])

  return (
    <>
      <Head>
        <title>Log Out</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Hero */}
      <main className="relative flex min-h-screen flex-col items-center justify-center bg-primary">
        <GenericCard className="min-w-[40vh] min-h-[60vh] flex flex-col items-center justify-center gap-y-3">
          <Image 
            src="/gradprep.png"
            width={120}
            height={120}
            alt="gradprep logo"
            className="mb-7"
          />
          <p>Anda berhasil keluar dari akun.</p>
        </GenericCard>
      </main>
    </>
  );
}
