import { MentorCard, SearchInput } from "@/components/elements";
import Lottie from "lottie-react";
import Head from "next/head";
import Help from "public/assets/lottie/help.json";

export default function Mentors() {
  return (
    <>
      <Head>
        <title>Mentors</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Hero */}
      <main className="relative flex min-h-screen flex-col items-center justify-start">
        <div className="relative h-[60vh] w-full bg-primary text-white">
          <div className="absolute bottom-0 right-[5vw] w-[20vw]">
            <Lottie animationData={Help} loop={false} />
          </div>
          <div className="container mx-auto flex h-full w-full flex-col items-start justify-start gap-y-8 pt-36">
            <h2>Temukan mentor yang tepat untuk pendidikanmu!</h2>
            <SearchInput
              placeholder="Cari mentor berdasarkan kata kunci  ..."
              className="max-w-[60%]"
            />
          </div>
        </div>
        <div className="relative min-h-[90vh] w-full bg-white">
          <MentorCard
            data={{
              userId: "12312321",
              name: "wee",
              email: "wee@mail.com",
              ppUrl: "https://placekitten.com/900/500",
              cvUrl: "",
              experiences: [
                {
                  organization: "Universitas Indonesia",
                  title: "Dosen",
                  startPeriod: "2022-01-01",
                  endPeriod: "2023-01-01",
                },
              ],
              bio: "lover",
              education: "Computer Science",
              expertise: "Information Retrieval",
            }}
          />
        </div>
      </main>
    </>
  );
}
