import { type User } from "@prisma/client";
import Head from "next/head";
import { useEffect, useState } from "react";
import { api } from "@/utils/api";
import { useRouter } from "next/router";
import Lottie from "lottie-react";
import Help from "public/assets/lottie/help.json";
import { Button, SearchInput } from "@/components/elements";
import { RiFile2Fill, RiFile2Line, RiFileImageLine } from "react-icons/ri";
import Image from "next/image";
import { IMentorNew } from "@/components/elements/Cards/MentorCard/interface";

export default function MentorDetailPage() {
  const router = useRouter()
  const id = router.query.id as string

  const fetchMentor = api.userData.getUserInformationById.useQuery({ id: id })
  const [data, setData] = useState<IMentorNew | undefined>(undefined);

  useEffect(() => {
    void setData(fetchMentor.data as IMentorNew)
  }, [fetchMentor.data])
  

  return (
    <>
      <Head>
        <title>Mentor {data?.name}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Hero */}
      <main className="relative flex min-h-screen flex-col items-center justify-start">
        <div className="relative h-[40vh] w-full bg-primary text-white">
          <div className="absolute bottom-0 right-[5vw] w-[20vw]">
            <Lottie animationData={Help} loop={false} />
          </div>
          <div className="container mx-auto flex h-[12vh] w-full flex-row items-start justify-start gap-x-3 pt-[27vh]">
            <div>
              { data?.image && <Image
                src={data.image}
                width={140}
                height={140}
                alt="mentor profile picture"
                className="rounded-full"
              /> }
            </div>
            <div>
              <h2 className="">
                {data?.name}
              </h2>
              <p>{data?.experiences[0]?.title}</p>
              <RiFile2Fill size={24} color="#0d0d0d" className="mt-2"/>
            </div>
          </div>
        </div>
        <div className="container flex flex-col md:flex-row gap-8 mt-[10vh] w-full">
          <div className="md:w-[70%] bg-gray-50 border border-gray-400 rounded-[15px] p-10">
            <p>TODO</p>
            <p className="font-bold">Bio</p>
            <p>{data?.bio}</p>
            <hr className="my-3"/>
            <p className="font-bold">Experiences</p>
            {data?.experiences.map((exp, i) => (
              <div key={i} className="ml-6">
                <p>{exp.organization}</p>
                <p>{exp.title}</p>
              </div>
            ))}
            <hr className="my-3"/>
            <p className="font-bold">Education</p>
            {data?.education.map((edu, i) => (
              <div key={i} className="ml-6">
                <p>{edu.school}</p>
                <p>{edu.field}</p>
              </div>
            ))}
          </div>
          <div className="md:w-[30%] bg-gray-50 border border-gray-400 rounded-[15px] p-10 flex flex-col items-center text-center gap-1">
            <p className="font-bold">Mentoring Topics</p>
            <p>{data?.expertise}</p>
            <hr className="mt-8"/>
            <Button variant={"primary"} size={"md"}>Request Session</Button>
            <p>This mentor has completed <b>XX</b> sessions!</p>
          </div>
        </div>
      </main>
    </>
  );
}
