import Lottie from "lottie-react";
import { Toaster } from "react-hot-toast";
import Image from "next/image";
import { api } from "@/utils/api";
import { useEffect, useState } from "react";
import Head from "next/head";
import { useRouter } from "next/router";

export default function ViewProfilePage() {
  const getUser = api.userData.getCurrentUserInformation.useQuery()
  const router = useRouter();

  /* eslint-disable  @typescript-eslint/no-explicit-any */
  const [data, setData] = useState<any>();

  useEffect(() => {
    console.log(getUser.data);
    void setData(getUser.data);
  }, [getUser.data]);

  useEffect(() => {
    if (data && !data.isOnboarded) {
      void router.push("/user/onboarding")
    }
  }, [data, router])

  return (
    <>
      <Head>
        <title>Mentor {data?.name}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Hero */}
      <main className="relative flex min-h-screen flex-col items-center justify-start">
        <div className="relative h-[40vh] w-full bg-primary text-white">
          <Toaster />
          <div className="container mx-auto flex h-[12vh] w-full flex-row items-start justify-start gap-x-3 pt-[27vh]">
            <div>
              {data?.image && (
                <Image
                  src={data.image}
                  width={140}
                  height={140}
                  alt="mentor profile picture"
                  className="rounded-full"
                />
              )}
            </div>
            <div>
              <h2 className="">{data?.name}</h2>
              <p className="font-bold">{data?.role}</p>
            </div>
          </div>
        </div>
        <div className="container mt-[10vh] flex w-full flex-col gap-8 md:flex-row">
          <div className="rounded-[15px] border border-gray-400 bg-gray-50 p-10 md:w-full">
            <p className="font-bold">Bio</p>
            <p>{data?.bio}</p>
            <hr className="my-3" />
            <p className="font-bold">Education</p>
            {data?.education.map((edu: any, i: number) => (
              <div key={i} className="ml-6 flex">
                {/* <p>{`${i}. `}</p> */}
                <p className="font-medium">{edu.school}</p>
                <p>{" – "}</p>
                <p>{edu.field}</p>
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
